// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'australiasoutheast';
  process.env['SSHCERT'] = 'test/containerCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstCntnGCreate3147/providers/Microsoft.ContainerService/containerServices/xplatContainer5189?api-version=2016-03-30')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/a06574e1-c0c9-4406-a771-2d69968f398a?monitor=true&api-version=2016-03-30',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/a06574e1-c0c9-4406-a771-2d69968f398a?api-version=2016-03-30',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': 'a06574e1-c0c9-4406-a771-2d69968f398a',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '5d128857-7581-4985-93e6-89b5d699e5a6',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040623Z:5d128857-7581-4985-93e6-89b5d699e5a6',
  date: 'Sun, 10 Apr 2016 04:06:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstCntnGCreate3147/providers/Microsoft.ContainerService/containerServices/xplatContainer5189?api-version=2016-03-30')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/a06574e1-c0c9-4406-a771-2d69968f398a?monitor=true&api-version=2016-03-30',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/a06574e1-c0c9-4406-a771-2d69968f398a?api-version=2016-03-30',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': 'a06574e1-c0c9-4406-a771-2d69968f398a',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '5d128857-7581-4985-93e6-89b5d699e5a6',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040623Z:5d128857-7581-4985-93e6-89b5d699e5a6',
  date: 'Sun, 10 Apr 2016 04:06:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/a06574e1-c0c9-4406-a771-2d69968f398a?api-version=2016-03-30')
  .reply(200, "{\r\n  \"operationId\": \"a06574e1-c0c9-4406-a771-2d69968f398a\",\r\n  \"startTime\": \"2016-04-10T04:06:21.7837334+00:00\",\r\n  \"endTime\": \"2016-04-10T04:06:21.9087434+00:00\",\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': '1c1e46fe-7532-4579-80d1-f1efb79c2735',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14974',
  'x-ms-correlation-request-id': 'eac8d6c0-8e1f-405c-83bd-8d843ba7173b',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040654Z:eac8d6c0-8e1f-405c-83bd-8d843ba7173b',
  date: 'Sun, 10 Apr 2016 04:06:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/a06574e1-c0c9-4406-a771-2d69968f398a?api-version=2016-03-30')
  .reply(200, "{\r\n  \"operationId\": \"a06574e1-c0c9-4406-a771-2d69968f398a\",\r\n  \"startTime\": \"2016-04-10T04:06:21.7837334+00:00\",\r\n  \"endTime\": \"2016-04-10T04:06:21.9087434+00:00\",\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': '1c1e46fe-7532-4579-80d1-f1efb79c2735',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14974',
  'x-ms-correlation-request-id': 'eac8d6c0-8e1f-405c-83bd-8d843ba7173b',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040654Z:eac8d6c0-8e1f-405c-83bd-8d843ba7173b',
  date: 'Sun, 10 Apr 2016 04:06:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstCntnGCreate3147/providers/Microsoft.ContainerService/containerServices/xplatContainer2505?api-version=2016-03-30')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/053576fb-1bed-4f53-96cb-cb10d1f5b712?monitor=true&api-version=2016-03-30',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/053576fb-1bed-4f53-96cb-cb10d1f5b712?api-version=2016-03-30',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': '053576fb-1bed-4f53-96cb-cb10d1f5b712',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': 'f402fceb-eee7-498b-88ca-5aa8e82b4783',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040657Z:f402fceb-eee7-498b-88ca-5aa8e82b4783',
  date: 'Sun, 10 Apr 2016 04:06:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstCntnGCreate3147/providers/Microsoft.ContainerService/containerServices/xplatContainer2505?api-version=2016-03-30')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/053576fb-1bed-4f53-96cb-cb10d1f5b712?monitor=true&api-version=2016-03-30',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/053576fb-1bed-4f53-96cb-cb10d1f5b712?api-version=2016-03-30',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': '053576fb-1bed-4f53-96cb-cb10d1f5b712',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': 'f402fceb-eee7-498b-88ca-5aa8e82b4783',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040657Z:f402fceb-eee7-498b-88ca-5aa8e82b4783',
  date: 'Sun, 10 Apr 2016 04:06:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/053576fb-1bed-4f53-96cb-cb10d1f5b712?api-version=2016-03-30')
  .reply(200, "{\r\n  \"operationId\": \"053576fb-1bed-4f53-96cb-cb10d1f5b712\",\r\n  \"startTime\": \"2016-04-10T04:06:56.181273+00:00\",\r\n  \"endTime\": \"2016-04-10T04:06:56.337526+00:00\",\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '189',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': '627124d6-1a0b-4799-a7dd-dd4b4ca5c3b4',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14972',
  'x-ms-correlation-request-id': '3855ce97-8b97-4932-9061-ec4ff0f0c08f',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040728Z:3855ce97-8b97-4932-9061-ec4ff0f0c08f',
  date: 'Sun, 10 Apr 2016 04:07:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.ContainerService/locations/australiasoutheast/operations/053576fb-1bed-4f53-96cb-cb10d1f5b712?api-version=2016-03-30')
  .reply(200, "{\r\n  \"operationId\": \"053576fb-1bed-4f53-96cb-cb10d1f5b712\",\r\n  \"startTime\": \"2016-04-10T04:06:56.181273+00:00\",\r\n  \"endTime\": \"2016-04-10T04:06:56.337526+00:00\",\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '189',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': '6d8fb542-dd65-48cb-9954-9a384a89dc05_131031808034968975',
  'x-ms-request-id': '627124d6-1a0b-4799-a7dd-dd4b4ca5c3b4',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14972',
  'x-ms-correlation-request-id': '3855ce97-8b97-4932-9061-ec4ff0f0c08f',
  'x-ms-routing-request-id': 'BRAZILUS:20160410T040728Z:3855ce97-8b97-4932-9061-ec4ff0f0c08f',
  date: 'Sun, 10 Apr 2016 04:07:28 GMT',
  connection: 'close' });
 return result; }]];