// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addEnvironment(new profile.Environment({
    name: 'BrazilUSCloud',
    portalUrl: 'http://go.microsoft.com/fwlink/?LinkId=254433',
    publishingProfileUrl: 'http://go.microsoft.com/fwlink/?LinkId=254432',
    managementEndpointUrl: 'https://management.core.windows.net',
    resourceManagerEndpointUrl: 'https://brazilus.management.azure.com/',
    sqlManagementEndpointUrl: 'https://management.core.windows.net:8443/',
    hostNameSuffix: 'undefined',
    sqlServerHostNameSuffix: '.database.windows.net',
    activeDirectoryEndpointUrl: 'https://login.microsoftonline.com',
    commonTenantName: 'undefined',
    storageEndpoint: 'undefined',
    galleryEndpointUrl: 'https://gallery.azure.com/'
  }));

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['BrazilUSCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
};

exports.scopes = [];

 exports.randomTestIdsGenerated = function() { return ['xplatTstVmssGCreate8014','xplattestnic9491','xplatteststorage1670','xplatteststorage29743','xplatteststorage32005','xplatteststoragecnt1170','xplatteststoragecnt2598','xplatteststoragecnt37154','xplattestvnet2306','xplattestsubnet6220','xplattestipdns398'];};